
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ROR_recipe_microservice_development

test:
  <<: *default
  database: ROR_recipe_microservice_test

production:
  <<: *default
  database: ROR_recipe_microservice_production
  username: ROR_recipe_microservice
  password: <%= ENV['ROR_recipe_microservice_DATABASE_PASSWORD'] %>
